services:
  backend:
    build:
      context: ./actix-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./actix-backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/principium
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: principium
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5434:5432'

volumes:
  pgdata:
